// <auto-generated />
using System;
using SystemTray.Storage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace SystemTray.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0-preview6.19304.10");

            modelBuilder.Entity("SoftU2F.Console.Storage.ApplicationData", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<uint>("Counter");

                    b.HasKey("Id");

                    b.ToTable("ApplicationDatum");
                });

            modelBuilder.Entity("SoftU2F.Console.Storage.KeyPair", b =>
                {
                    b.Property<string>("KeyHandle");

                    b.Property<byte[]>("ApplicationTag");

                    b.Property<string>("Label");

                    b.Property<byte[]>("PrivateKey");

                    b.Property<byte[]>("PublicKey");

                    b.HasKey("KeyHandle");

                    b.ToTable("KeyPairs");
                });
#pragma warning restore 612, 618
        }
    }
}
