// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using U2FLib.Storage;

namespace U2FLib.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("U2FLib.Storage.ApplicationData", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<uint>("Counter");

                    b.HasKey("Id");

                    b.ToTable("ApplicationDatum");
                });

            modelBuilder.Entity("U2FLib.Storage.KeyPair", b =>
                {
                    b.Property<string>("KeyHandle")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("ApplicationTag");

                    b.Property<string>("Label");

                    b.Property<byte[]>("PrivateKey");

                    b.Property<byte[]>("PublicKey");

                    b.HasKey("KeyHandle");

                    b.ToTable("KeyPairs");
                });
#pragma warning restore 612, 618
        }
    }
}
