on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Publish Daemon

jobs:
  publish:
    name: Upload Release Asset
    runs-on: windows-latest
    steps:
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true
          
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Build project # This would actually build your project, using zip for an example artifact
        run: |
          dotnet publish --configuration Release --runtime win10-x64 --self-contained --output Release/win10-x64 --version-suffix ${{ github.run_number }} SoftU2FDaemon/SoftU2FDaemon.csproj
          Compress-Archive -Path Release/win10-x64\* -DestinationPath SoftU2FDaemon-SCD-win10-x64-${{ github.run_number }}.zip


      - name: Upload Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            SoftU2FDaemon-SCD-win10-x64-${{ github.run_number }}.zip
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
